### ISSUE TITLE
Not every plugin are listed

### ISSUE THREAD

**Issue by Gustry** [lutraconsulting/qgis-report-plugin#13] opened 2016-05-11 05:45 UTC
Maybe I misunderstood the plugin, but I have an empty line in the dropdown menu and a lot of plugin are missing.
What is the purpose of this dropdown menu ? The plugin can't detect which plugin crashed ?

![3858](https://cloud.githubusercontent.com/assets/1609292/15171080/d83d8c66-1775-11e6-908f-340a2e978603.png)

Thanks in advance

**Comment by PeterPetrik** [comment] 2016-05-11 06:57
Thanks for reporting this, the plugin can detect which plugin crashed, however inasafe plugin crashed during loading, which was not expected by report plugin. I will fix it asap.

Can you please delete your access token from github account and generate new one? Because you have accidentally copied your secret access token to the screenshot

**Comment by Gustry** [comment] 2016-05-11 07:21
Ahah, yes I removed it. I was busy with the dropdown menu that I forgot that I put my token ;-)

So what is the purpose of this dropdown menu if the plugin detect which plugin crashed ?

**Comment by PeterPetrik** [comment] 2016-05-11 08:20
the problem is that the plugin crashed during its load (call of classFactory). So the plugin itself it not yet registered in the QGIS. This should not happen in production-use plugins, because classFactory is basically what you call every time you start QGIS as the first thing. In case the exception/error that is produced **any time later** (that means when you actually use the plugin), the report-plugin will correctly catch it and detect the misbehaving plugin

I will fix it in the way that it will list even not loaded plugins, but it may not correctly work in this kind of situations anyway (I mean when error is produced during plugin loading). The order of plugin loading is pretty much random, and it may happen that report-plugin is scheduled for loading after the crushing plugin ....

**Comment by Gustry** [comment] 2016-05-11 08:27
Ok, no problem. I understood that my case was special.
I'm developing on inasafe right now and I have installed your plugin this morning.

But now, inasafe is fixed, the plugin is correctly launched in qgis. But I still have some issues with qgis-report : 

```
TypeError: string indices must be integers 
Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/report/report_plugin.py", line 81, in run
    show_report_dialog()
  File "/home/etienne/.qgis2/python/plugins/report/report_plugin.py", line 34, in show_report_dialog
    report_dialog = main_widget.MainWidget(last_error)
  File "/home/etienne/.qgis2/python/plugins/report/main_widget.py", line 38, in __init__
    self._load_settings()
  File "/home/etienne/.qgis2/python/plugins/report/main_widget.py", line 110, in _load_settings
    self._set_chosen_plugin(plugin)
  File "/home/etienne/.qgis2/python/plugins/report/main_widget.py", line 99, in _set_chosen_plugin
    self._plugin_selected()
  File "/home/etienne/.qgis2/python/plugins/report/main_widget.py", line 186, in _plugin_selected
    self._enable_widgets()
  File "/home/etienne/.qgis2/python/plugins/report/main_widget.py", line 150, in _enable_widgets
    self._load_labels()
  File "/home/etienne/.qgis2/python/plugins/report/main_widget.py", line 154, in _load_labels
    labels = self.github.get_labels()
  File "/home/etienne/.qgis2/python/plugins/report/github_utils.py", line 95, in get_labels
    ret += [l['name']]
TypeError: string indices must be integers
```

qgis-report itself can catch the exception. I saw the dropdown, I still have an empty line.

**Comment by PeterPetrik** [comment] 2016-05-11 08:31
wow, wondering how that "l" went there. Fixing that right now

**Comment by PeterPetrik** [comment] 2016-05-11 08:37
Fixed in https://github.com/lutraconsulting/qgis-report-plugin/commit/15eafcb340e8b3b3af009221dd7a5a40c0325227

**Comment by PeterPetrik** [comment] 2016-05-11 09:15
@Gustry this happens when your token is invalid see #24
Please recreate the token, make sure you copy-paste there the valid new one without any spaces around and try again

**Comment by PeterPetrik** [comment] 2016-05-11 09:16
Closing this issue for listing inactive plugins (fixed in https://github.com/lutraconsulting/qgis-report-plugin/commit/07eaed9272280923264f3454a2273c09bca3a463).

**Closed as completed by PeterPetrik** 2016-05-11 09:16 UTC
Labels: bug
